cmake_minimum_required(VERSION 3.16)
project(vf_hmc LANGUAGES CXX)
add_executable(vf_hmc vf_hmc.cpp)
target_compile_features(vf_hmc PRIVATE cxx_std_20)
find_package(OpenMP REQUIRED)
target_link_libraries(vf_hmc PRIVATE OpenMP::OpenMP_CXX)
if(MSVC)
  target_compile_options(vf_hmc PRIVATE /O2 /W4)
else()
  target_compile_options(vf_hmc PRIVATE -O3 -Wall -Wextra)
endif()
